### ISSUE TITLE
Detection problem when calling mmdection

### ISSUE THREAD

**Issue by lilixj** [LZGMatrix/BOP19_CDPN_2019ICCV#7]
Current Dataset: lmo
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
[                                                  ] 0/95, elapsed: 0s, ETA:Traceback (most recent call last):
  File "inference.py", line 170, in <module>
    main()
  File "inference.py", line 162, in main
    result_dict = single_gpu_test(model, data_loader)
  File "inference.py", line 61, in single_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/zhuyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhuyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/zhuyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/D/lxj/PoseEst/mmdetection-1.2.0/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
TypeError: forward() missing 1 required positional argument: 'img_metas'

**Comment by lilixj** [comment]
After I config mmdetection and it has been tested to work normally, when I execute "python inference lmo", I encounter above problem, does anyone know how to solve it or what the problem is?

**Comment by wangg12** [comment]
The code requires mmdet version <= 1.0.0, so it may have some bug when using mmdet==1.2.
